---
title: "Pre-cohort engagement"
format:
  html:
    code-fold: true
    code-summary: "Show the code"
---

*Could also be titled: attracting research teams?*



## Overview

Since 2018 we have iterated on a coordination strategy that works well for coordinating with partners and attracting research teams to participate in the Champions Cohort. This coordinating work begins \~2.5 months before the cohort will start, and the time allows for preparing text for communications (announcement emails, twitter, and website and google form), having a \~1 month long nomination period, selection, and 1:1 interviews with each team lead prior to the cohort starting.

We focus our engagement/recruitment of team leads (i.e. PIs) to coordinate for their teams.

## Planning document

We make a copy of our [Openscapes-CohortPlanningDoc](https://docs.google.com/document/d/1uzQ-hic0Kn0pNyeb9VwVNDwMYRetZgiXkQ2mZIe_TXk/edit?usp=sharing) to share with our Partners. This planning document is to help us finalize dates and text language for announcing and coordinating our Openscapes Cohort. We have found this procedure to work best: 

- We set date-times for all Cohort Calls that work for all of us that are involved with leading them. Cohorts meet twice monthly for 2 or 4 months via Zoom for 1.5 hours on a specific week day on alternating weeks. 
- We announce the opportunity and the date-times and ask for team leads to nominate their teams. We’ve found setting the date-times in advance (no doodle) streamlines scheduling and it makes this event seem more official. Plus, having team leads commit to the times on behalf of their whole teams creates more buy-in. (More info on what is a team and how to pick teams here: <https://www.openscapes.org/faq>). 

The following is a high-level overview of what is in the Planning Doc and announcement, with example text.

## Announcement: call for nominations

Once we finalize schedules and text in the CohortPlanningDoc, we announce the opportunity as ask team leads to nominate their teams. 

### Email, Twitter, Fliers

Our partners will distribute the announcement via their channels through email, listeserves, fliers, etc. We can also tweet the announcement from our account (<https://twitter.com/openscapes>). All announcements will link to the opportunity's post on the Openscapes events page (see next). 

### Openscapes events page

We create a post on the Openscapes Events page with details about the opportunity. This can be cross-posted elsewhere. It will be linked in any email correspondance, fliers, tweets, etc. Here is an example: <https://openscapes.github.io/events/posts/2021-05-07-css-champions>

### Google Form

The events page links to a Google Form (~10 minutes) that research leads fill out to nominate their team to participate. Below is example text.

```{r, eval=FALSE}
Title: FDD Openscapes Champions Cohort

Hello! This form is to nominate your research group to participate in the Openscapes Champions program for FDD. This opportunity is open only to lab groups affiliated with FDD. Please provide one nomination per research group, by August 20, 2021. See [<https://openscapes.github.io/events/posts/2021-09-17-XXXX>](https://openscapes.github.io/events/posts/2021-05-07-XXXX) for more details.

\

-   **First name**

-   **Last name**

-   **Email address**

-   **Web presence (website, Twitter, GitHub) (optional)**

-   **ORCID (see <https://orcid.org/>)  (optional)**

-   **Which institution are you affiliated with?**

-   **How did you hear about this FDD Openscapes opportunity?**

-   **Who is the lead of the research group you are nominating?**

-   **Are you this research group lead? If not please explain**

-   **[Any other FDD specific questions]**

-   **Briefly tell us why your team would be a good candidate for our Champions cohort.** We aim to invite a diverse group of researchers to learn together. Please tell us how your interests, career position, expertise, reproducible research efforts, and/or potential of future contribution to the open science community will help make a productive and creative cohort. Or simply tell what you hope to learn by joining and what types of data challenges you face.

-   **What is your research focus?** (15 words or fewer)

-   **Please share any relevant projects you might have worked on** (links appreciated)

-   **Have you attended an "open" event before?** For example through the National Center for Ecological Analysis and Synthesis (NCEAS), Mozilla, or The Carpentries? Please share.

-   **Openscapes is committed to providing a welcoming community for all participants.** One of our priorities is to support and amplify the diversity of researchers participating in open science. Therefore, we strongly encourage applications from women, people of colour, LGBTQ, differently-abled individuals, and any other underrepresented minorities in research. If you identify with any of these groups and wish to share this information with us, or wish to share specific needs to participate over Zoom, please use the box below. (optional)

-   **For this opportunity, you will participate as a team with up 1-4 other members of your research group. Please describe who some of those individuals might be.** Please see openscapes.org/faq for more details on selecting a team. 

-   **Please confirm you and your team are available for all program events:**

    -   **May 7, 12:00-1:30pm PST**

    -   **May 21, 12:00-1:30pm PST**

    -   **June 4, 12:00-1:30pm PST**

    -   **June 18,12:00-1:30pm PST**

-   **Where will you be joining from?** This helps us understand time zones as we coordinate.

-   **Please read and agree to our code of conduct before you submit your application to participate.** [paste short summary, link to [full CoC](https://www.openscapes.org/code-of-conduct/)). (required).

    -   Radio buttons: agree, disagree

-   **Thank you for the information. Anything else you'd like to share?**

-   **Submit button: "Apply"**

\
**Confirmation message:** Thank you for the nomination. We will be in touch in late August.
```

## Selection and coordination

*We have example text for these that we will pull into a template Google Doc and link here* <!---TODO: https://docs.google.com/document/d/1LzSL-ZzX2VFDh1Av1_uuADiB4Jc1F5j2dM_mo3d1fyg/edit#--->

### Selection rubric

We have a selection rubric and work with partners to select participating teams.

### Email to confirm team leads

We send an email to potential team leads, asking them for a 1:1 intro call.

### Send out Google Calendar Invites

We add team leads to the Openscapes Community Calendar's Cohort Calls. We also email them with more details and ask them to reply cc'ing their teams and scheduling 1:1 intro calls. Then we add the teams to the Calendar Invites. 

### 1:1 Intro calls

We use Google Calendar Appointment Slots to schedule 1:1s with each team lead. This is a way for us to get to know each other and to learn more about their team's needs. We schedule these 1:1's for ~1 month before the start of the cohort

## Cohort welcome

~1 week prior to the beginning of the Cohort, we email the full Cohort, welcoming everyone and sharing the plan. We request in advance they: 

- read Lowndes et al. 2017
- watch the SORTEE plenary recording (30 mins)

We'll also schedule the GitHub Clinic. 

