---
title: "Champions Program Operations"
format: html
---

*The following can be built into a statement of work with our Partners.* 

### Summary and Scope

[**Openscapes**](https://www.openscapes.org/) offers mentorship, training, coaching and community organizing centered around open data science to help teams develop collaborative practices that are more reproducible, transparent, inclusive, and kind. 
 
The Openscapes Approach supports the vision laid out by the National Academy of Science, Engineering and Medicine (NASEM)’s [Open Science by Design](https://www.nap.edu/catalog/25116/open-science-by-design-realizing-a-vision-for-21st-century) report. Our approach for doing better, more reproducible and inclusive team science in less time, is to first support scientists to create workflows that allow sharing with themselves (Future You) as well as with their teams and collaborators (Future Us). Future Us considers our teams, communities, and those who will be joining and continuing our work, whether that is next hours, weeks or decades ([Lowndes & Robinson, 2021](https://www.openscapes.org/blog/2021/08/01/sortee-plenary/)). 

Often we find that research teams are not sharing openly, internally among themselves. By considering and creating practices that support Future Us, the Openscapes approach helps research groups reimagine data analysis, develop modern data management and sharing skills that are of immediate value to them, and cultivate collaborative and inclusive research communities. Openscapes’ mentorship and community engagement approaches promote kinder science through technical tooling and diversity, equity, and inclusion, enabling increased efficiency and resilience for teams so that their work has more enduring impact.

[**Openscapes Champions**](https://www.openscapes.org/champions) is a mentorship and professional development opportunity for scientific research teams to explore open data science, including data management and sharing practices. It is a remote-by-design mentorship program that guides teams through the open data science landscape, empowers them as leaders, and welcomes them as part of the growing open community. Participants attend a Champions cohort series as a team with their research group in a cohort with other teams, together learning how to reframe data-intensive science as a collaborative effort rather than an individual burden. By discussing open software tooling and communities enabling reproducible research (e.g., R/RStudio, GitHub, metadata), participants develop collaborative skills, mindsets, and habits and establish shared practices for increased efficiency in their own research, while contributing to a more inclusive scientific culture.
 
Through the Champions cohort series, a cohort of 6-8 teams will meet 4 times over 2 months for 1.5-hour video calls. These small-time requirements over longer time frames enable incremental change, accountability, and community building within the realities of scientists’ busy schedules and varying expertise and needs. 

**Champions Cohort Goals**  

The goals of the Champions cohort series is to help teams normalize open data science discussions, identify shared needs and how to address them, and how to think ahead so they can more effectively onboard themselves and others on new (and existing) projects. We will:    

- Create leaders within a research community to champion open science best practices 
- Help participants adopt open science tooling and practices, including reproducibility, openness, collaboration, inclusion, share methods sooner 
- Explore practices that build trust and community within and across teams (across career stages)
- Improve ease and confidence in  sharing imperfect work within their teams and cohort
- Empower participants to become champions for more collaborative, open science within their teams and transform their own workflows. 

### Services

Openscapes will provide the curriculum, agendas, and lead the remote cohort series. The curriculum will be based on the lesson series available at: <https://openscapes.org/series>. 

1. Openscapes mindset, Better science in less time
1. Team culture, Technical strategies for future us
1. Coding communities, Research examples
1. Sharing Pathways forward

Additionally, we lead: 

- GitHub Clinics for hands-on team skill-building
- Community engagement leading up to, throughout, and after the Cohort
 
Openscapes will co-create recruiting materials (e.g., openscapes.org/events), and will lightly email participants preceding, throughout, and following the workshop. The Openscapes team will provide curriculum, support coordination, and teach the remote workshop series along with workshop helpers. We are beginning to evaluate the Champions program as well.

**Note: Participants attend as teams.** Participants attend as teams including team leads (e.g., PIs, program managers, faculty) and team members (e.g., analysts, post-docs, students, technicians). The goals of combining team leads and members across varying skill sets and expertise are:
1)    Everyone sees the value in open project management and data sharing practices
2)    Leads enable their team members to invest time in learning skills and developing lab workflows
3)    Team members have guidance, agency, and support to incorporate open science, data management and sharing concepts into their research
4)    Everyone contributes to growing the community of practice within the research group, institution, and online, in whatever capacity their role and circumstances allow. See also the Champions Program FAQ.