---
title: "Leading Cohort Calls"
format: html
---

Everyone on the Openscapes team should be a confident leader and active contributor during Cohort Calls. We are open, kind, and help each other as we prepare and facilitate. This is how we lead each call, with additional steps for the first call.

We also experiment with ideas and incorporate them into subsequent calls within a Cohort as needed. For example, we experimented with Google Jamboards in Summer 2022, and then in Fall added an "am I doing Openscapes right" to agenda, and we will be providing more Pathways support in the future.

## Roles

There are three main roles when we lead Cohort Calls. When folks are assisting a Cohort Call, they often help take notes, and monitor chat, and create breakout rooms.

-   **Tech Host**: Zoom co-host, create breakout groups, monitor chat & Slack, help note-taking
-   **Facilitator**: Zoom co-host, leads discussion as noted in the Agenda
-   **Teacher**: Talks through demos and slides

Note-taking should focus on capturing questions and conversations and less about slides. Copying questions from the Chat into the Agenda is also really helpful.

-   Example Roles: [NOAA NMFS](https://github.com/Openscapes/cohort-planning/issues/1)

## Before Cohort Calls

-   Prepare the Agenda; see [Pre-cohort tech setup: Cohort Call Agendas](/champions/pre-cohort-tech.qmd#agenda-kyber)
-   Review Roles, with particular focus on facilitator and tech host roles

## During Cohort Calls

Software to have open:

-   Zoom, with Chat and Participants open
-   Slack for back-channeling if needed, likely not
-   Agenda
-   Quicklinks Issue, Participants List (example: [NOAA NMFS](https://github.com/Openscapes/cohort-planning/issues/1))
-   Welcome folks as they join, ask them to rename themselves in Zoom to identify their team (helps us for breakout groups)
-   Monitor the chat
-   Help with note-taking. Both to capture what folks are saying and to role-model. Help others engage.

::: {.callout-tip collapse="true"}
## Example chat welcome text

Welcome! Please write your name in Roll Call as you join: \[ doc \]

**If you need access to the doc please put your email in chat**

And please rename yourself with how you'd like to be called and your team name (hover over your name or video \> 3 dots \> Rename)
:::

### Making breakout rooms

Breakout rooms are generally random or as teams.

-   Random: set up breakout rooms just before we go into them; for example if you set them up during roll call and more folks join before the reflections, you won't be able to create new rooms for them
-   Teams: this takes more time and you'll need the participant list in front of you

### Guest teachers' presentations

Screenshare! This way we can edit out the recording if groups would like to share these presentations publicly, for example with NOAA NMFS' Em Markowitz' [Data to Product Workflows](https://www.youtube.com/watch?v=CyqOjQwQLy8).

## Between Cohort Calls

Between Calls there are tasks for the Openscapes team and for the Champions teams (that the Openscapes team helps support).

### Field Notes / Debriefs

We ask all co-leads and assistants to write down thoughts about how the cohort went - these are internal "field notes" that will help us improve between Cohort Calls and across Cohorts.

Prompts to answer include:

-   Top-of-mind i.e. what would you tell your roommate?
-   Brief summary of how it went
-   Rose / Bud / Thorn - something that was good, developing, or tricky

We write field notes in the OpenscapesCohortPlanning folder: DebriefsDigests Google doc (as of Fall 2022), with one doc for all Cohort Calls. We draft Digests in this same doc.

### Digests

We send digests the week following each Cohort Call (early, on Monday or Tuesday). This gives people a touch point in the week between Calls. Digests include links to the Call's agenda, the Call's goals, slides, and some excerpts from the shared notes.

Call 1 Digest is sent via email, and following the GitHub Clinic, the rest are sent via GitHub Issues as a way to continue practicing throughout the cohort. When posting as an issue, tag the cohort GitHub team like `@Openscapes/2022-noaa-sefsc-summer-cohort` so they get email notification.

We develop these in a single "DebriefsDigests" Google Doc along with our field notes (above). With the AFSC Mentors we would cowork on this during a debrief Seaside Chat immediately after each Cohort Call.

::: {.callout-tip collapse="true"}
## Example DebriefsDigests doc template

### Pre-Call prep 15 mins before start

Julie last minute checks: good internet?

Stef during call

-   turn on live transcript
-   Share this Debriefs doc link with team to add async notes
-   Set co-hosts
-   Paste in Zoom chat: Welcome! Here's our shared Agenda where we can all take notes, please say hello in Roll Call as you join: LINK
-   Add slides link to chat when relevant
-   Hit record (local); stop during breakouts & restart. Add red RECORD text in doc
    -   PAUSE in between, not STOP (pause makes it one recording, stop makes separate recordings)
-   Breakout rooms - - create them 5-10 mins before opening so you can manually move ppl before opening rooms, if desired e.g. distribute Mentors to different rooms
    -   don't make them too early

Stef or Julie post-call

-   Upload video to CohortFolder

Tips when presenting

-   At start of call, open all your slide decks at 1st slide, especially when you're presenting twice in one day
-   As you start to present a deck, put slide link into chat
-   Ask guest teachers to screenshare so we can post video
 

### Debriefs

*These are internal "field notes" that will help us improve between Cohort Calls and across Cohorts. Described in [Approach Guide](https://openscapes.github.io/approach-guide/champions/leading-cohort-calls.html#field-notes)*

***Prompts to answer include:***

-   *Top-of-mind (what would you tell your roommate?)*
-   *Brief summary of how it went*
-   *Rose / Bud / Thorn - something that was good, developing, or tricky*

#### Call 1

Julie

-    
-    

Stef

-    
-    

Co-lead

-    
-    

Co-lead

-    
-    

### Digests

*Call 01 Digest is sent by email. Subsequent digests are posted as GitHub Issues, following the GitHub Clinic in Call 02. Stef recommends pasting the Digest content in RStudio Visual, then look at the Source, edit, copy-paste into GitHub issue. This has required fewer edits than using a Google doc to Markdown plugin.*

*Structure is*

-   *"yay this thing from the call"*
-   *below is a short digest*
-   *(Digest 1) we've invited you to private Cohort channel in Openscapes Slack. Link to [orientation](https://openscapes.github.io/approach-guide/approach/tooling.html#slack)*
-   *(Digest 1) we've sent calendar invite to Coworking in weeks between Cohort Calls. These are optional. Can use the time for team Seaside Chats*
-   *(Digest 1) add your GitHub username*
-   *Sign off*
-   *Structured Digest content*

#### Call 1

Hi All!

It's exciting to start our NAME Openscapes Champions Cohort and meet you all in Zoom! We introduced a lot of concepts; we will explore them more together in the next sessions. Below is a light digest of Call 01, including a reminder about your Seaside Chat to think through your Pathway trailhead.

As a reminder of tasks for next time: have your first 'seaside chat' with your team and discuss where are you now? 

We'll send each of you an invitation to Openscapes Slack. Here's a short [Slack orientation](https://openscapes.github.io/approach-guide/approach/tooling.html#slack) to help you get comfortable. The 2023-cohort-name channel is a private space to connect with each other, and other community channels are to engage with folks from previous cohorts and the broader Openscapes Community. Joining Slack is optional, another tool for you to experiment with.

Have a good week,

Stef, Julie, Co-lead, Co-lead


**Digest: Cohort Call 01 \[ year-cohort-name \]**

Openscapes_CohortCalls \[ year-cohort-name \] (TODO: add link) Google folder - contains agendas, recordings, pathways 

https://openscapes.github.io/year-cohort-name/ (TODO: add link) - cohort webpage

**Goals**: We started working towards a common understanding of the Openscapes mindset and what your pathway forward looks like for your team.

**Task**: please see the Agenda doc (under Closing) (TODO: add link) for more details

1.  Have a Seaside Chat (meet with your team) & reflect together on what you've learned so far 
2.  (optional) Attend Coworking. We've  sent a calendar invite for DATE, TIME. Come prepared to get your own work done, ask questions, or listen in to other conversations and screensharing.

**Slide Decks:**

-   Openscapes mindset ([slides](https://docs.google.com/presentation/d/1fXgrWU5AMrZwgvpjs2J0dRT9x1Tc-IZyQIn8yPZSGM8/))
-   Better science for future us ([slides](https://docs.google.com/presentation/d/1tE3pQ2ObNU68iG4uTIlMuSN4dguvn-cOvwtoM-c9L-w/))

**A few lines from shared notes in the Agenda doc**

*Note: no need to add agenda subheadings or group notes under them*

-   
-   
-   
:::

See Digest examples:

-   [2023-noaa-nwfsc-fall](https://github.com/nmfs-openscapes/2022-noaa-nwfsc-fall/labels/digest)
-   [2022-nasa-champions](https://github.com/NASA-Openscapes/2022-nasa-champions/labels/digest)
-   [2022-noaa-afsc](https://github.com/Openscapes/2022-noaa-afsc/labels/digest)
-   [2021-fdd](https://github.com/Openscapes/2021-fdd/labels/digest)
-   [2021-noaa-nmfs](https://github.com/Openscapes/2021-noaa-nmfs/labels/digest)

### Coworking

We started coworking with Cohorts in fall 2021. It's a nice practice that our team does together (to work on your own but have a buddy available over Zoom) and it's nice to offer as a practice to the Champions too. Champions have said they appreciate this as a practice to take back to their research groups and it's also a nice way to continue to build community and a learning culture and practice talking about data needs and screensharing.

We set up an hour of Coworking in the weeks between Cohort Calls. These are optional times where folks can work on their own things but also share and ask questions. Here is an agenda template [OpenscapesCoworking \[ year-cohort-name \]](https://docs.google.com/document/d/1dT4KHvlS18rGxXVLhtvsCOWT_5kmxKgBkVwnhMf3WN0/edit?usp=drive_link).

::: {.callout-tip collapse="true"}
## Example Coworking agenda

We share what we're going to work on, and then work quietly and then check in at the end as well. We also make breakout rooms for Q&A if folks want to screenshare and talk things out.

-   Brief intros to share what we're planning to work on
-   Create breakout rooms based on topics, and you can move yourself. Today:
    -   ProjectBoards
    -   ChattierRoom - Eli there for Q&A. Pop in and out.
-   Brief closing to share what you did & any resources!
:::

#### Different flavors of coworking

Our practice of coworking has evolved, particularly through running 4 simultaneous NOAA NMFS Cohorts in Fall 2022. We use a few flavors now. The take home message is that people can experiment with this practice and see what works for them!

-   Cohort coworking is outlined above and is the standard format we use in Openscapes Champions Cohorts between Calls. In some sessions, we would invite a participant in advance to "screenshare-and-tell" something they did or learned relating to the previous lesson (in the first 5 minutes to get things going). Some teams used these for their Seaside Chats.
-   Themed coworking was an experiment in Fall 2022 as a way to bring participants together across Cohorts. These were 1.5-hr sessions with Eli Holmes giving a lesson, followed by coworking in breakout rooms. Typically people stayed in the main room for Q & A.\
-   Small group or 1:1 coworking is described in ([Butland & Penfold 2020](https://www.cscce.org/2020/02/04/online-co-working-partnerships-are-community-of-practice-in-action/)).

### Seaside Chats

Champions teams will hold Seaside Chats, and we share suggested topics each Cohort Call.

### Git / GitHub drop-in help

After the GitHub Clinic lesson it might be helpful to offer optional drop-in help sessions for folks to get set up with Git and GitHub on their local machines.

Eli Holmes recorded 4 short videos that people should watch before attending:

1.  [Setting GitHub Desktop Preferences](https://youtu.be/0PVOPL6i3MQ) (2.5 mins)

2.  [Cloning a repository](https://youtu.be/acIwQO1eOtw) (2 mins)

3.  [Pulling and pushing changes to GitHub](https://youtu.be/cQgn3_w27_8) (3.5 mins)

4.  [Turning an existing directory into a Git repository and pushing to GitHub](https://youtu.be/9BTpiTQPyu8) (2 min)

In the Fall 2022 NMFS Cohorts we learned that many people needed help finding where Git was installed on their Windows machines, for example. Collaborative notes with screenshots were added in Google doc: OpenscapesCoworkingCross-Cohort \[ 2022-nmfs-fall \]

::: {.callout-tip collapse="true"}
## Example invitation to Git / GitHub drop-in sessions

We've scheduled 30-minute drop-in sessions for those who want to get their computer connected to Git and GitHub. Drop in and we'll get you set up!

What should I install beforehand? [GitHub Desktop](https://desktop.github.com/). This is a great option and is especially good if your GitHub repos have files from multiple programs (R, Python, Excel, Word, images, data files). If you install GitHub Desktop, you will have Git installed with that. If you don't get GitHub Desktop, then you will need to have Git installed.

Once you have GitHub Desktop installed, watch the short videos from Eli Holmes to see how to get things set up.

1.  [Setting GitHub Desktop Preferences](https://youtu.be/0PVOPL6i3MQ) (2.5 mins)

2.  [Cloning a repository](https://youtu.be/acIwQO1eOtw) (2 mins)

3.  [Pulling and pushing changes to GitHub](https://youtu.be/cQgn3_w27_8) (3.5 mins)

4.  [Turning an existing directory into a Git repository and pushing to GitHub](https://youtu.be/9BTpiTQPyu8) (2 min)

Give it a try and if you have any trouble getting connected, come to the drop-in sessions and we'll help!

-   Date / time (click to add to your Google Cal)
-   Date / time (click to add to your Google Cal)

See [Tip: Click URL to add to your Google Calendar](pre-cohort-tech.qmd#google-workspace) for instructions on how to implment this.
:::

## First Cohort Call

The first Cohort Call has additional setup and followup, since we introduce and follow up on things that we discuss together (i.e. Slack)

### Beforehand

Set up Slack Channel with all assistants

::: {.callout-tip collapse="true"}
## Example slack text: team coordination

Hi All, Excited for today! We'll share the \[ Agenda \] in chat, and expect that some folks will still need to request access. We'll ask them to share their emails in chat so that we can add them quickly - to the folder if possible. If you add access for someone, would you also add their email to \[ OpenscapesParticipants \] and I'll revisit afterwards. Thanks!
:::

### Afterwards

**Slack invites**

-   See [how-to instructions](pre-cohort-tech.qmd#slack) in Cohort Tech Setup
