---
title: "Lesson Planning"
---

The [Openscapes Champions Series](https://openscapes.github.io/series/) describe the lessons we currently teach, with each lesson represented as a book chapter with linked slides. During Cohort Calls we teach from the slides and not from the book chapters; the chapters will ultimately be a stand-alone resource for self-paced learning (this is a work in progress).

Each lesson is a 10-15 minute slide deck or demo, and there are two lessons per Cohort Call. Lessons are taught followed by an activity so particpants can reflect how topics apply to their own work (see more about [agenda structure](/champions/pre-cohort-tech.html#agenda-structure)). 

## Lessons Review

We review our planned lessons before we teach. We add relevant updates and links; there are new examples and features that we add! It's a balance of adding these to slides or book chapters so that the slides have up-to-date information but aren't too overwhelming.

We also invite guest teachers, and offer to pay them for their time. 

## Lesson Planning

We'll be collaborating to develop new lessons with partners for our four-month cohorts! We do this with a spreadsheet to plan lessons and implement them closer to teaching dates so that we can be responsive to cohort needs. Planning includes topics, slide decks, activities, efficiency tips, and Seaside Chat topics. More here soon.

Examples: 

- [SASI Champions Lesson Plan](https://docs.google.com/spreadsheets/d/1nYS_EDhddmG3ILwqmO432tUsjjshlhHnxuoSM4r2cs4/edit#gid=0)
- [ NASA Champions Lesson Plan](https://docs.google.com/spreadsheets/d/1wDhV0ncbYuqVPv7jCE0y1E6TsWXeGKIfddUmsr3LmBU/edit?usp=sharing)

New lessons will build from the core lessons we lead for two-month cohorts (from the [Series welcome](https://openscapes.github.io/series/)):

Cohort Call Topics          | Series Chapters |      Seaside Chat Topics
------------------|----------------------|---------------------------
1. Openscapes mindset, better science in less time | [mindset](https://openscapes.github.io/series/mindset.html), [better science in less time](https://openscapes.github.io/series/better-science.html) | Pathway - where are you now
2. GitHub Clinic: publishing & project management | [publishing](https://openscapes.github.io/series/core-lessons/github/github-pub.html), [project management](https://openscapes.github.io/series/core-lessons/github/github-issues.html) | Shared organizing with GitHub
3. Team culture and data strategies for future us | [team culture](https://openscapes.github.io/series/team-culture.html), [data strategies](https://openscapes.github.io/series/data-strategies.html) | Onboarding docs, code of conduct
4. Open communities and coding strategies for future us | [open communities](https://openscapes.github.io/series/communities.html), [coding strategies](https://openscapes.github.io/series/coding-strategies.html) | Pathway - next steps
5. Pathways share and next steps |  | 


## Agenda structure {#agenda-structure}

Cohort Calls are 1 hour 30 minutes. Each Call is different, but they have this core structure:

-   Roll call with ice breaker
-   Welcome with Code of Conduct reminder and land acknowledgement
-   Lesson with activity 1
-   Lesson with activity 2
-   Efficiency and inclusion tips

Activities include prompted silent journaling or breakout groups followed by group discussion. Breakout groups are 3-4 people each; some are random, some group by team, and some group leads together and members together.


