---
title: "Post-Cohort followup"
format: html
---

## GitHub Checklist

This issue is to help track the post-cohort setup, following the [approach-guide](https://openscapes.github.io/approach-guide/champions/post-cohort-followup.qmd) and focused on the engagement and tech setup after dates are set.

These TODO's are for @jules32 and also will include @erinmr

-   [ ] Prep Survey - @jules32
-   [ ] Call 5 Digest, with survey - @jules32
-   [ ] Blog summary - @erinmr
-   [ ] Add songs to spotify - @jules32
-   [ ] Write cards & stickers - @erinmr starts

## Thank you email (Digest 5)

We send a thank you email via GitHub Issues as a Call 5 Digest

## Survey

Here is the [survey template](https://docs.google.com/forms/d/e/1FAIpQLSdu7fJCWfTScw5-P62fjmuzmA7Y0x2O1yWhpDpZe5-THjCyjQ/viewform?usp=sf_link) we sent out to Champions following the cohort.

In some cases we've sent out a reminder email:

::: {.callout-tip collapse="true"}
## Example reminder email

Hi All!

We wanted to thank you all again for being a part of our SASI Openscapes Cohort this fall and appreciate all you were able to give with everything else going on. Yesterday's screenshare-and-tells and discussions were super and it's exciting to see the momentum you have going forward. We're excited to stay in touch (Slack, Twitter, etc) and will be sending out a last digest soon!

We'd appreciate your feedback in this \[5-min survey\] so we can improve based on feedback of what did and didn't work. Additionally, please email/slack us a snail-mail address for your team so that we can send a thank you card and stickers!

Thanks again, and we hope you all have a safe and healthy break.

Cheers,

Julie, Erin, Emma, and Lenny
:::

## Honoraria for Guest Teachers

::: {.callout-tip collapse="true"}
## Example email text: Openscapes Honorarium

Hi \[Name\],

Thank you for presenting at the Openscapes Champions Cohort Series on \[June 25, 2021\].

In appreciation of your time spent preparing and presenting at our event, we are able to provide a \$150 stipend. I've attached two forms here that UCSB needs in order to process this for you. Please send them back to me and let me know if you have further questions.

Thank you very much, Cheers, Julie
:::

## Follow up with Partners

Send thank you / report out email

## Blog

## Thank you letters & stickers

We love snail mail. This is a chance to send a written thank you to teams and also share physical Openscapes stickers.

## 3-Month Check-Ins

*Modeled after SGCI*

-   very limited structure on the call
-   revisit repo
-   share summaries from pathways

*Prompts originally from Gayle Hagler, EPA*

Elements to consider including:

-   What were you working on/your situation that motivated you to participate?
    -   Who were your team members and how did you work together on data?
-   Did you see any shifts (now or forthcoming) in your personal or team’s research approaches as the result of the experience? This could include how your team interacts, new technical practices, any “ripple effects” to other projects.

::: {.callout-tip collapse="true"}
## Example Google Calendar text: CSS Openscapes 3-month check-in (optional)

Hello CS&S Champions! This is an optional 3-month check-in to reconnect and share updates since our Cohort. You can also always connect with the community more on Slack, and through upcoming community calls and other events: https://openscapes.org/events
:::

::: {.callout-tip collapse="true"}
## Example EPA Google Calendar text: Reunion! CEMM's 2024 Openscapes cohort

As part of their routine practice for cohorts, Openscapes is hosting a one-time regrouping of our 2024 cohort for a 3-month check-in on how things are going. This is optional and will be informal! This is a good opportunity to share about progress, ask questions, and help one another with stuck points as we all have been putting to practice what we learned.

Thanks,
Gayle
:::

::: {.callout-tip collapse="true"}
## Example Email text: EPA Openscapes cohort reunion (optional)
Hi everyone,

A heads-up that our Openscapes cohort reunion is coming up after Thanksgiving (Nov 30th)!

This will be an informal and fun meeting for the group to reconnect and share how their project team has progressed since our cohort sessions concluded in the spring. “Show and tell” items are welcome (e.g., a screenshare of a GitHub site or a slide from a recent talk you gave), but teams should not feel any need to prepare presentations. We will also share updates about our second cohort of research teams that has been in planning for a few months!

I am looking forward to seeing everyone and wish you all wonderful holidays between now and our meeting.

Best,
Gayle
:::

::: {.callout-tip collapse="true"}
## Example Email text to Fred Hutch: Openscapes 3-month checkin DATE (optional)
Hi All!

Wow. It's been 3 months since we last got together to hear about your Pathways! On Tuesday, we'll be in Zoom 10 - 11 am PT (Zoom link) for an optional 3-month check-in to reconnect and share updates since our Cohort. We've started an agenda in our Coworking doc.

Ideas for things folks could share informally:

- What motivated you to join? (Related - How did your lab members work together on data or code?)
- Did you see any shifts (now or forthcoming) in your personal or lab's approaches as the result of the experience? This could include how your team interacts, new technical practices, any “ripple effects” to other projects.

It's a time for all participants to informally share what you’ve worked on, little wins, where you need help. We look forward to watching you advance on your journeys!

Openscapes_CohortCalls [ 2023-fred-hutch ] (LINK) Google folder - contains agendas, recordings, pathways 
https://openscapes.github.io/2023-fred-hutch - Cohort website

You can also always connect with the community on Slack, and through upcoming community calls and other events: https://openscapes.org/events.

Cheers,
Stef, Julie, Sean, Monica, Liz
:::

::: {.callout-tip collapse="true"}
## Example Email text: Openscapes NOAA Fisheries 3-month checkin
Hello Openscapes Champions!
(Bcc everyone from 4 Fall 2022 NOAA Fisheries Cohorts)

Time has flown by since we completed our Fall Openscapes Cohorts. We look forward to watching you advance on your journeys! If you can make it, please join us for a 3-month check in so we can hear what everyone is up to.

(optional!) Wednesday, February 22, 2023
1:00 - 2:00 pm PT / 4:00 - 5:00 pm ET
Not already in your Calendar? Join via Zoom

Cheers,
Stef and Julia
:::


## Social Hours

Learn about our Summer monthly [Social Hours](../approach/seaside-chats.qmd#social-hours) in Seaside Chats.

## Qualitative Data Analysis

We take debrief notes at the end of each Cohort Call that can inform future [Qualitative Data Analyses and assessments](../approach/qual-assessment.qmd).
