---
title: "Pre-cohort engagement"
---

## Overview

Pre-cohort engagement is focused on potential participants for the Cohort.

**We focus our engagement/recruitment on both individuals and team leads** (i.e. PIs) to coordinate for their teams. This is so there is buy-in for the team to invest time into learning with the Openscapes Cohort. The Cohort will explore software and practices that help teams collaborate more efficiently, and are not only for people who code or work with data.

We begin this engagement once we've scheduled the dates, \~2 months before the Cohort begins: see the Program Design Chapter for details about timing.

Depending on the Cohort, recruitment may happen by the partners internally rather than by Openscapes. Approaches we've iterated/formalized can still help in these cases - for example having a public webpage with all information (which gives it some official "weight" and is also a single place to point folks to for details), and focusing on engaging and building trust with team leads so that their teams are approved to spend time.

## Announcement: call for nominations

Once we finalize schedules and text in the CohortPlanningDoc, we announce the opportunity asking individuals to apply or team leads or PI's to nominate their teams, depending on the nature of the cohort.

### Websites, Email, Socials

Our partners will distribute the announcement via their channels through email, listservs, website, etc. We can also share the announcement from our social accounts ([Mastodon](https://fosstodon.org/@openscapes); [Bluesky](https://bsky.app/profile/openscapes.bsky.social){.uri}). All announcements will link to the opportunity's post on the Openscapes Events page (see next).

### Openscapes Events page

We create a post on the [Openscapes Events](https://openscapes.org/events) page with details about the opportunity. This can be cross-posted elsewhere. It will be linked in any email correspondence, posts, partners' websites, etc. Here are some examples.

**European Space Agency (ESA) Openscapes Champions, 2026** [Event page](https://openscapes.org/events/2026-04-15-esa-champions/) + [GitHub Source](https://github.com/Openscapes/website-new/tree/main/events/2026-04-15-esa-champions).

::: {.callout-tip collapse="true"}
## Text for event page, **ESA Champions 2026**

# ESA Openscapes Champions Program Spring 2026

An Openscapes Cohort to learn open science approaches for your daily workflows, including FAIR principles for Earth Observation

## Join us to do better science in less time, together

**This is a professional development and leadership opportunity for European Space Agency (ESA) affiliated researchers and people supporting ESA research** to explore open data science practices and make incremental and sustainable change, no matter where you are starting from. The spring 2026 Champions Cohort will run from **April 15th to June 10th, 2026**, meeting biweekly 14:00 - 15:30 GMT. Please nominate yourself **by March 25, 2026**.

Jump to [how to apply](https://openscapes.org/events/2026-04-15-esa-champions/#sec-how-to-apply), below.

[Openscapes](https://openscapes.org/) is an approach and a movement that helps researchers find each other and feel empowered to conduct data-intensive science ([Lowndes et al. 2019](https://openscapes.org/events/2026-04-15-esa-champions/#ref-lowndes2019); [Robinson and Lowndes 2022](https://openscapes.org/events/2026-04-15-esa-champions/#ref-robinson2022)). Since 2019, Openscapes has mentored over 600 researchers at universities across the US and at NASA and NOAA, helping to shift institutional culture to develop climate solutions with open science ([Lowndes et al. 2024](https://openscapes.org/events/2026-04-15-esa-champions/#ref-lowndes2024)).

[ESA EarthCODE](https://earthcode.esa.int/) is part of the ESA’s vision for Earth Observation (EO) Open Science and Innovation. EarthCODE enables scientists to find and reuse research data, use integrated EO platforms to develop scientific workflows, and publish them by automating the “[FAIR](https://www.go-fair.org/fair-principles/?)ification” process - making digital assets more Findable, Accessible, Interoperable, and Reusable. Key EarthCODE stakeholder groups in its first phase include researchers in the Earth System Science Hub, Phi Lab, and ESA Science Clusters.

## Program details

[Openscapes Champions](https://www.openscapes.org/champions/) is a remote-by-design mentorship program for researchers to explore open data science practices. For ESA Openscapes, participants also spend time experimenting and planning FAIR principles for Earth Observation and EarthCODE. [Core lessons](https://openscapes.github.io/series/what-to-expect.html#cohort-calls) include open mindset; GitHub for publishing and project management; team culture, data strategies for future us; coding strategies for future us; open communities.

**We will meet as a cohort five times over two months**, on alternating Wednesdays in April - June, 2026.

-   **Dates**: April 15, 29, May 13, 27, June 10.

-   **Times**: 14:00 - 15:30 GMT.

-   **Where**: remotely, via Zoom.

-   **Who**: ESA-affiliated researchers (postdoctoral fellows, graduate students, principal investigators, other academic researchers) and people supporting ESA research. Preference will be given to Science Hub, Phi Lab, and ESA Cluster researchers if we reach capacity.

-   **Cost**: Free; this opportunity is supported by the ESA EarthCODE Project through a contract to Openscapes.

-   **Expected time commitment**: 6hrs/month for 2 months is an expected time commitment. This accounts for 3 hours/month of synchronous Zoom calls, optional coworking times, and collaborating with your peers to strengthen shared workflows.

For more information about the Openscapes and our Champions Program, see “Openscapes as a mechanism for Crossing the Chasm between idea and adoption in science” ([slides](https://docs.google.com/presentation/d/1B3dSYr0eptGgDL_V6EZchU_BrJ-uS3v2K-miDkbhSqc/)) and [What to Expect](https://openscapes.github.io/series/what-to-expect). For stories from over 25 past Openscapes Champions Cohorts from NASA Earthdata, NOAA Fisheries, other government agencies and academic groups, please browse these [blog posts](https://openscapes.org/blog#category=champions).

## How to apply

To nominate yourself, please **fill out the nomination form** (*link disabled here*) **by March 25**. Open science is collaborative! We encourage you to sign up with a colleague or two – it is more fun to participate together and you have more accountability. You don’t need to be working on the same project, only an interest in improving workflows.

Questions? Contact hello \@ openscapes.org.

This opportunity is funded by the [European Space Agency EarthCODE](https://earthcode.esa.int/).

## References

*(Reference list is generated via Zotero integration with RStudio + Quarto, creates a `references.bib` file)*

Lowndes, Julia S. Stewart, Halley E. Froehlich, Allison Horst, Nishad Jayasundara, Malin L. Pinsky, Adrian C. Stier, Nina O. Therkildsen, and Chelsea L. Wood. 2019. “Supercharge Your Research: A Ten-Week Plan for Open Data Science.” *Nature*, October. <https://doi.org/10.1038/d41586-019-03335-4>.

Lowndes, Julia S. Stewart, Anna M. Holder, Emily H. Markowitz, and Kathryn Doering Corey Clatterbuck Amanda L. Bradford. 2024. “Shifting Institutional Culture to Develop Climate Solutions with Open Science.” *Ecology and Evolution*, April. <https://doi.org/10.1002/ece3.11341>.

Robinson, Erin, and Julia S. Stewart Lowndes. 2022. “The Openscapes Flywheel: A Framework for Managers to Facilitate and Scale Inclusive Open Science Practices,” October. https://doi.org/<https://doi.org/10.31223/X5CQ02>.
:::

**NOAA Fisheries Openscapes Champions, 2025** [Event page](https://openscapes.org/events/2025-10-07-nmfs-champions-2025/) + [GitHub source](https://github.com/Openscapes/website-new/tree/main/events/2025-10-07-nmfs-champions-2025).

::: {.callout-tip collapse="true"}
## Text for event page, **NOAA Fisheries Champions, 2025**

# NOAA Fisheries Openscapes Champions Program Fall 2025

120 Openscapes Champions in 3 Cohorts for NOAA’s National Marine Fisheries Service

**The NOAA Fisheries Open Science Champions cohorts are coming (back) this fall.** [Sign up by Sept 8](https://nmfs-openscapes.github.io/champions)! This is a workflow transformation & leadership opportunity. The Champions cohorts directly support staff and teams as they work on workflow modernization and data science modernization goals. This program is a key part of workforce training and support associated with the [Fisheries Data Modernization Efforts](https://www.fisheries.noaa.gov/science-data/data-modernization-efforts-noaa-fisheries); read about the [2024 cohorts](https://www.fisheries.noaa.gov/science-blog/open-science-momentum-noaa-fisheries). The Champions cohorts help staff across all centers and offices address cross-regional data sharing challenges using cloud and Open Science solutions and implement reproducible data science workflows and tooling.

All details, dates, sign-ups, FAQs, and scheduled “Ask Us Anything” sessions: <https://nmfs-openscapes.github.io/champions>.

We especially encourage people interested in [cloud migration and data preservation](https://docs.google.com/presentation/d/1Q6zerBOYfSr-Sw0YTz2JV8OOskjw_0oGOIM2WSMmS84/edit?slide=id.g3720335bad7_1_989#slide=id.g3720335bad7_1_989) to sign up, although you do not need to be interested in this theme to apply. We will be teaching the Champions core lessons and some will be tailored to help people think through what this year’s theme - reimagine data and workflows in the cloud - might mean for their own work.

[Openscapes](https://openscapes.org/) is an approach for doing better science in less time ([Lowndes et al. 2017](https://openscapes.org/events/2025-10-07-nmfs-champions-2025/#ref-lowndes2017)). We help research groups reimagine data analysis, develop modern skills that are of immediate value to them, and cultivate collaborative and inclusive research communities. Openscapes’ mentorship and community engagement approaches center on open data science as kinder science ([Lowndes et al. 2019](https://openscapes.org/events/2025-10-07-nmfs-champions-2025/#ref-lowndes2019)), enabling increased efficiency and resilience for teams so that their work has more enduring impact.

[Openscapes Champions](https://openscapes.org/initiatives#champions-program) is an open data science mentorship program for science teams. It is a multi-month program that is designed to ignite incremental and sustainable change within research teams and beyond. It helps teams get their own work done, while building skills and community within the realities of scientists’ busy schedules, varying expertise and needs. **From October through December 2025, 120 NMFS researchers will participate in 3 concurrent cohorts.**

### Resources

-   [NMFS Openscapes](https://nmfs-openscapes.github.io/)

-   [NMFS Openscapes Champions Cohorts](https://nmfs-openscapes.github.io/champions.html)

-   Blog posts about [NMFS Openscapes](https://openscapes.org/blog#category=noaa-fisheries) and past [Champions](https://openscapes.org/blog#category=champions)

-   [Nationwide Openscapes Training at NOAA Fisheries Science Centers: Facilitating Collaboration, Skill-sharing, and Open Science](https://openscapes.org/blog/2023-01-24-noaa-nmfs-fall/)

-   [NMFS Open Science](https://nmfs-opensci.github.io/)

## References

*(Reference list is generated via Zotero integration with RStudio + Quarto, creates a `references.bib` file)*

Lowndes, Julia S. Stewart, Benjamin D. Best, Courtney Scarborough, Jamie C. Afflerbach, Melanie R. Frazier, Casey C. O’Hara, Ning Jiang, and Benjamin S. Halpern. 2017. “Our Path to Better Science in Less Time Using Open Data Science Tools.” *Nature Ecology & Evolution* 1 (6): 0160. <https://doi.org/10.1038/s41559-017-0160>.

Lowndes, Julia S. Stewart, Halley E. Froehlich, Allison Horst, Nishad Jayasundara, Malin L. Pinsky, Adrian C. Stier, Nina O. Therkildsen, and Chelsea L. Wood. 2019. “Supercharge Your Research: A Ten-Week Plan for Open Data Science.” *Nature*, October. <https://doi.org/10.1038/d41586-019-03335-4>.
:::

**Fred Hutch Openscapes Champions, 2025** [Event page](https://openscapes.org/events/2025-04-09-fred-hutch/) + [GitHub Source](https://github.com/Openscapes/website-new/tree/main/events/2025-04-09-fred-hutch).

### Google form to apply

Potential participants can sign up via Google Form (or Google Sheet - see below).

**Google Form:** The event page links to a Google Form (\~10 minutes) that individuals use to self-nominate, or research leads fill out to nominate their team to participate. Below is example text. Remember to change the settings (so it's not restricted to any particular respondents) and have the thank you message say when they'll expect to hear from us. To get started, it's often easiest to copy and modify (fork!) the most relevant or recent Google form.

::: {.callout-tip collapse="true"}
## Text for Google form - ESA Champions 2026

Hello! This form is to nominate yourself to participate in the Openscapes Champions program for the European Space Agency (ESA). This opportunity is open to researchers and people supporting research affiliated with ESA. **Please nominate yourself by March 25**. Open science is collaborative! We encourage you to sign up with a colleague or two who are keen to explore pathways to more open science.

**See [Event page](https://openscapes.org/events/2026-04-15-esa-champions/) for full details.**

-   **First name\***

-   **Last name\***

-   **Email address\***

-   **Group** (e.g. ScienceHub, Phi Lab, ESA Cluster, or others)\*

-   **Earth science discipline** (e.g. ocean, biodiversity, meteorology, etc)\*

-   **Research focus** (15 words or fewer)\*

-   **Web presence** (website, GitHub; optional)

-   **ORCID ID** (see <https://orcid.org/>) (optional)

-   **Briefly describe how you use ESA data in your research.** (links appreciated) \*

-   **Briefly tell us why you are a good candidate for our Champions cohort.** We aim to invite a diverse group of researchers to learn together. Please tell us how your interests, career position, expertise, reproducible research efforts, and/or potential of future contribution to the open science community will help make a productive and creative cohort. Or simply tell what you hope to learn by joining and what types of data challenges you face.\*

-   **Openscapes is committed to providing a welcoming community for all participants.** One of our priorities is to support and amplify the diversity of researchers participating in open science. Therefore, we strongly encourage applications from women, people of colour, LGBTQ+, disabled individuals, or any other underrepresented and under-served minorities in research. If you identify with any of these groups and wish to share this information with us, or wish to share specific needs to participate over Zoom, please use the box below. (optional)

-   **Please confirm you are available** for these 5 cohort calls, held at 14:00 - 15:30 GMT. (It is ok if you need to miss one or two sessions; we record so folks can review)\*\
    *use form checkboxes*

    -   April 15
    -   April 29
    -   May 13
    -   May 27
    -   June 10

-   **Please read and agree to our code of conduct** before you submit your application to participate. <https://openscapes.org/code-of-conduct>.\*

    -   Radio buttons: agree, disagree

-   **Thank you for the information. What else would you like to share?**

\
**Confirmation message:** Thank you for nominating yourself! We will be in touch by March 30.
:::

::: {.callout-tip collapse="true"}
## Text for Google form - NASA Champions, 2022

Title: NASA Openscapes Champions Cohort

Hello! This form is to nominate your research group to participate in the NASA Openscapes Champions Cohort. This is a professional development and leadership opportunity for scientists that use data from NASA's Earth Observing System Data and Information System (EOSDIS) Distributed Active Archive Centers (DAACs) and are interested in collaborative open data science practices and migrating their workflows to the cloud.

This opportunity is open only to research groups that use data from NASA DAACs. Please provide one nomination per research group, by February 1, 2022. See https://nasa-openscapes.github.io/champions for more information about NASA Openscapes, and https://openscapes.org/faqs for more details about team composition.

-   **First name**

-   **Last name**

-   **Email address**

-   **Web presence (website, Twitter, GitHub) (optional)**

-   **ORCID (see <https://orcid.org/>)  (optional)**

-   **Which institution are you affiliated with?**

-   **How did you hear about this FDD Openscapes opportunity?**

-   **Who is the lead of the research group you are nominating?**

-   **Are you this research group lead? If not please explain**

-   **\[Any other NASA specific questions\]**

-   **Briefly tell us why your team would be a good candidate for our Champions cohort.** We aim to invite a diverse group of researchers to learn together. Please tell us how your interests, career position, expertise, reproducible research efforts, and/or potential of future contribution to the open science community will help make a productive and creative cohort. Or simply tell what you hope to learn by joining and what types of data challenges you face.

-   **What is your research focus?** (15 words or fewer)

-   **Please share any relevant projects you might have worked on** (links appreciated)

-   **Have you attended an "open" event before?** For example through the NASA Cloud Hackathon, Pangeo, Mozilla, The Carpentries, or National Center for Ecological Analysis and Synthesis (NCEAS)? Please share.

-   **Openscapes is committed to providing a welcoming community for all participants.** One of our priorities is to support and amplify the diversity of researchers participating in open science. Therefore, we strongly encourage applications from women, people of colour, LGBTQ, differently-abled individuals, and any other underrepresented minorities in research. If you identify with any of these groups and wish to share this information with us, or wish to share specific needs that would help make your experience participating in this remote workshop series easier or more comfortable, please use the box below. (optional)

-   **For this opportunity, you will participate as a team with up 1-4 other members of your research group. Please describe who some of those individuals might be.** Please see openscapes.org/faq for more details on selecting a team. 

-   **Please confirm you and your team are available for all program events:**

    -   **May 7, 12:00-1:30pm PST**

    -   **May 21, 12:00-1:30pm PST**

    -   **June 4, 12:00-1:30pm PST**

    -   **June 18,12:00-1:30pm PST**

-   **Where will you be joining from?** This helps us understand time zones as we coordinate.

-   **Please read and agree to our code of conduct before you submit your application to participate.** \[paste short summary, link to [full CoC](https://www.openscapes.org/code-of-conduct/)). (required).

    -   Radio buttons: agree, disagree

-   **Thank you for the information. Anything else you'd like to share?**

-   **Submit button: "Apply"**

**Confirmation message:** Thank you for the nomination. We will be in touch in late August.
:::

**Google Sheet:** For some cohorts, like recent NOAA Fisheries cohorts, a Google Form isn't the right way to have potential participants to share their interest, particularly as team form. NOAA Fisheries partners have found it best to coordinate internally with a Google Spreadsheet, that may or may not be linked from an events page. Here is a [Template Sign-Up Google Sheet](https://docs.google.com/spreadsheets/d/1TkgQ1VNYK4MeY9WhO_OEp1AHeTqf16v7VvCWwSOD5M0/edit?usp=sharing) from SEFSC & AFSC.

::: {.callout-tip collapse="true"}
## Email to share opportunity - ESA Champions 2026

To: group of researchers\
Subject: Invitation to ESA Openscapes Champions Program

Dear \[ \],

You are invited to participate in the Openscapes Champions Program this spring! This is a professional development and leadership opportunity for European Space Agency (ESA) affiliated researchers and people supporting ESA research.

This is a free, cohort-based remote-by-design program for researchers to learn open science approaches for your daily workflows and strengthen collaboration and reproducibility. The program will be held as five sessions in April-June 2026. Nominations are open until March 25. Please see the [event page](https://openscapes.org/events/2026-04-15-esa-champions/) for full details, and this [form where you can sign up]{.underline} \[LINK to form\] to participate.

Open science is collaborative! I encourage you to join with a colleague or two who are keen to explore these practices together.

I’m happy to answer any questions.

Cheers,

\[ \]
:::

## Selection and coordination

Selection and coordination varies somewhat depending on the Cohort. Academic cohorts are most often nominated by faculty PI, so first email communications are with them and then team/lab/group members are added as a second step as teams confirm, and finally we write the cohort as a whole. Government cohorts are often selected within the agency with less focus on "team lead", and so email communications are sent out to the whole cohort from the start. Below are examples of the Academic cohort process, ending with the [Cohort Welcome](#cohort-welcome) email to the whole cohort - see there for examples for welcoming government groups as well.

*We have example text for these that we will pull into a template Google Doc and link here* <!---TODO: https://docs.google.com/document/d/1LzSL-ZzX2VFDh1Av1_uuADiB4Jc1F5j2dM_mo3d1fyg/edit#--->

### Selection rubric

We have a selection rubric and work with partners to select participating teams. Many groups have their own internal process however, and that's great.

### Email to confirm team leads

When teams have nominated themselves, we send an email to potential team leads with more details and ask them to reply cc'ing their teams and scheduling 1:1 intro calls.

::: {.callout-tip collapse="true"}
## Example email welcome to selected PIs

Subject: Welcome to the FDD Openscapes Champions Cohort 🎉

Dear \[PI\],

Thank you for nominating your team to participate in the FDD Openscapes Champions Cohort! We are excited for you to be a part of the cohort; this email is your official acceptance. To confirm you're still able to participate, please:

1.  **Book a 30-minute intro call on August 27 or 30** \[link to Google Cal booking page\] -- or suggest other times if that is not possible, preferably September 10. These are short intro calls with Openscapes and team leads to start getting to know each other, share more details about the Champions Program, learn about the team, how they work, their goals for the Cohort, and answer any questions.
2.  **Respond to this email, cc'ing your team members** (up to 4 others). We will then add you and your team to Google Calendar invites for all 4 Cohort Calls.

Our [cohort page](https://openscapes.github.io/2021-fdd/) details the dates and times, as well as some background about what to expect, Openscapes, and FDD. We will also email the full cohort prior to the Aug 29 start date.

Please let us know if you have any questions! We're looking forward to working and learning with you.

Cheers,\
Julie Lowndes, Openscapes
:::

### Email to confirm individuals

::: {.callout-tip collapse="true"}
## Example email welcome to selected NMFS individuals

Subject: Welcome to the NMFS Openscapes Champions Cohort 🎉

Hello All,

We are so excited to welcome you to the 2022 SEFSC Openscapes Champions Cohort! Our first Cohort Call is the first week of October and we wanted to share some information with you. Many thanks to Erica Rule for coordination and support in creating this opportunity, and to Adyan Rios and Molly Stevens who are co-leading this Cohort. This is one of four [NMFS Openscapes](https://nmfs-openscapes.github.io) Cohorts happening concurrently this Fall and we’ll create some opportunities for you to connect. 

The [Openscapes Champions Program](https://openscapes.org/champions) is designed for you to all participate actively with your team and across teams in the Cohort, so please come prepared to engage with your colleagues. Within your team and across teams we have a mix of backgrounds, technical/coding/data experience, responsibilities, and more – this is intentional. You are all welcome here and provide value to our Cohort; there are no technical prerequisites to participate. 

**Preparing for our Cohort. This week, please**:

1.  **Check that you’ve received Google Calendar invites for our 5 Cohort Calls**. If you have not received these invites, please let us know.

    1.  **Dates:** October 4, 18, November 1, 15, 29

    2.  **Times:** 10:00am - 11:30am PT

    3.  **Location:** Remotely, via Zoom (link will be added to Calendar invites)

2.  [**Book a 30-minute intro call the week of Sept 26**](https://calendar.google.com/calendar/u/0/selfsched?sstoken=UUx3MjBab3hoUGpLfGRlZmF1bHR8ZTcwNmUxNjRjMDQxMGNhMGRkZWY1OTYzN2I1YjVjNmU) – or suggest other times if that is not possible. These optional “1:1’s” are a chance for your team to meet the Openscapes team, learn more about what to expect, start thinking about your goals, and ask any questions. Please discuss with your team and book a time (one time per team).

3.  **Read before our first call[Lowndes et al 2017](https://www.nature.com/articles/s41559-017-0160)**: Our path to better science in less time using open data science tools.

**Additional Information.**

All Openscapes events abide by our[Code of Conduct](https://openscapes.org/code-of-conduct). We are dedicated to providing a positive learning environment for all. Please let us know if you require any accommodations or if there is anything we can do to make this cohort more accessible to you.

Will be recording all Cohort Calls. They will be available for you if you miss a meeting or to use as a reference, and to help us improve the program, but not shared publicly. If you have any concerns about being recorded, please let us know. We will also have live transcripts. 

“Seaside Chats”: In the alternating weeks when we do not meet as a cohort, your task will be to meet as a team to further discuss and apply what we learn to your work. We call these meetings “[Seaside Chats](https://github.com/Openscapes/seaside-chats)” and suggest you schedule them with your team now; people usually schedule these as 60-min meetings but you can make them whatever length you want. 

Optional “Coworking” sessions: times to implement what we’ve learned during Cohort Calls, where we work on our own projects at the same time together. Sometimes, this means quiet work with check-ins to break up the time, be accountable for, and get feedback on focused work, and sometimes this involves breakout rooms and screensharing to plan and problem solve. We’ll send Google Calendar invitations after our first Cohort Call.

Please let us know if you have any questions. Thank you for being a part of it; we have an exciting group assembled and we’re looking forward to getting to know all of you and strengthening relationships within the Cohort.

Cheers,

Julie Lowndes, Stefanie Butland (Openscapes)

Eli Holmes (NWFSC)
:::

#### Email to decline

Declining nominees is the worst.

::: {.callout-tip collapse="true"}
## Example email to decline nominees

Dear NAME,

Thank you for nominating your team to participate in the Openscapes Champions CS&S Cohort; we appreciate your interest in learning with us. This was our first open call and we had more interest than we expected, and have not been able to accept all of the great teams that applied. Unfortunately, this means that we are not able to include you in our CS&S cohort.

We will be looking to offer more opportunities like this one as we grow Openscapes as a program, and invite you to stay tuned through our (infrequent) newsletter and via Mastodon [\@openscapes\@fosstodon.org](https://fosstodon.org/@openscapes). There are also upcoming virtual opportunities at NCEAS, including through the Reproducible Research Techniques for Synthesis course in July.

Cheers,

Julie Lowndes and Erin Robinson

Co-Directors, Openscapes
:::

### Team setup and calendaring

Here's the process as the PIs confirm with their teams:

-   Add to OpenscapesParticipants \[ 2021-fdd \]
-   Add team leads and members to the Cohort Calls and optional Coworking sessions on the OpenscapesEvents Google Calendar. Use same Zoom link for both invites.
-   Reply all welcome email to team members with confirmation (example text below)

::: {.callout-tip collapse="true"}
## Example text for Google Calendar invites

It's helpful to add "Openscapes" as the first word in title of Calendar invite to distinguish it from many other invites in people's calendars.

### Openscapes Coworking - Fred Hutch Champions Cohort

description text: We set up an hour for Coworking in between Cohort Calls; these are optional times where folks can work on their own things but also share and ask questions. Julie and Stef will be there to answer questions. Want to have your Team Seaside Chat at this time? We'll make a breakout room for you.

Our Cohort folder [Openscapes_CohortCalls \[ 2023-fred-hutch \]](https://drive.google.com/drive/folders/1i-ZZRMvEHDwQ5vJZpX_P4ycqOTwAKnyM?usp=drive_link) has a Coworking Agenda doc where we take collaborative notes.

### Openscapes Fred Hutch Cohort Calls

description text: Cohort Calls for the [2023 Fred Hutch Openscapes Champions Cohort](https://openscapes.github.io/2023-fred-hutch/) Quicklinks: Shared Cohort Google Folder [Openscapes_CohortCalls \[ 2023-fred-hutch \]](https://drive.google.com/drive/folders/1i-ZZRMvEHDwQ5vJZpX_P4ycqOTwAKnyM?usp=drive_link)
:::

::: {.callout-tip collapse="true"}
## Example email welcome to team members

Thanks \[PI\],

And hi \[folks\], great to meet you all! OpenscapesParticipants \[ 2021-fdd \] is our growing participant list, would you all please update information for your row? We've also just sent Google Calendar invites and will be in touch more before our first Cohort Call on \[date\].

Looking forward to it,

Julie and Erin
:::

### Follow teams on Mastodon

As we are introduced to team leads and members, we follow them on Mastodon from the Openscapes account.

### 1:1 Welcome / Intro calls

These are short intro calls with Openscapes and team leads or teams, to start getting to know each other, share more details about the Champions Program, learn about the team, how they work, their goals for the Cohort, and answer any questions. This is a way for us to get to know each other and to learn more about their team's needs. We hold these \~3 weeks before the start of the cohort.

Schedule these calls in 2 half-day blocks of time to fit different time zones. Create \~10 separate Google calendar items with 25-minute meetings, each with a unique zoom link. For each meeting, click the 3-dots \> publish \> copy link; add list of times & their links to the Welcome email, inviting individuals and team leads to select a time and invite their team members.

Note: We do not use a [Google Calendar Appointment Schedule](https://support.google.com/calendar/answer/11608416) for these 1:1's because once a person books a meeting, it is not available to others. For large groups like NMFS Openscapes with 3 concurrent cohorts, we want multiple people and teams to be able to join the same welcome call.

Excerpt from welcome email:

**(Optional) Join a 25-minute welcome call Sep 24 or 25** – These optional calls are a chance for you to meet the Openscapes team and other NMFS colleagues in small groups, learn more about what to expect, start thinking about your goals, and ask any questions. If you’d like to join an intro call, you should select one of the times listed below and add it to your calendar. If you joined with a team, invite your other team members to come at the same time! 

-   **Wed Sep 24**

    -   9:00 am PT (add to your calendar \[LINKED\])

    -   9:30 am PT (add to your calendar)

-   **Thu Sep 25**

    -   1:00 pm PT (add to your calendar)

    -   1:30 pm PT (add to your calendar)

::: {.callout-tip collapse="true"}
## Example text in the Calendar slot:

Title: Openscapes Champions Welcome Call (optional)

Description: These optional welcome calls are a chance for you to meet the Openscapes team and other NMFS colleagues in small groups, learn more about what to expect, start thinking about your goals, and ask any questions. If you’d like to join an intro call, you should select one of the times listed in your welcome email and add it to your calendar. If you joined with a team, invite your other team members to come at the same time!
:::

Before the 1:1's, create an agenda for each call by copying Google doc: Template_Openscapes_IntroCall

::: {.callout-tip collapse="true"}
## Example agenda for 1:1 intro calls

**Openscapes Champions Cohort Intro Call**

\[ Participants \]\
27 August 2021\
30 minutes

**Agenda:**

-   Intros

    -    

-   Openscapes Champions Cohort

    -   2 months to think about where you are and where you want to go

    -   Focus on open science, collaboration, data, inclusion

    -   Geared towards adult learning -- focus on your own work

    -   Mentorship for you and your team (up to 5 total people)

        -   Don't need a shared project: idea is that there are common workflows across projects.

    -   What it's not: a coding workshop or webinar. Engaging discussions w/ your team and peers. 

    -   4x 1.5-hour Cohort Calls over Zoom, Sept-Oct 2021

        -   Seaside Chats (data-oriented meetings) on alternating weeks

            -   Distribute learning load and build leadership & resilience 

        -   1x GitHub Clinic -- publishing & collaboration from the browser

-   Team and whole research group

    -    

-   Goals for the next few months? -- start thinking about these

    -    

-    Other 

    -   \
:::

## Cohort welcome {#cohort-welcome}

Here is an example Cohort welcome email as a first email communication with a (government) group, and below is cohort welcome email when we have already been communicating with PIs, and then their teams individually.

::: {.callout-tip collapse="true"}
## Example email to welcome (government) cohort

**Welcome to Openscapes -- NMFS AFSC Champions Cohort**

Hello All,

We are so excited to welcome you to the 2022 AFSC Openscapes Champions Cohort! Our first Cohort Call is on January 28 and we wanted to share some information with you, including how to prepare for the cohort series. Em Markowitz, Josh London, and Megsie Siple from AFSC are assisting this cohort; we are all available to answer any questions so please do not hesitate to contact us. Many thanks to Jeremy Rusin for coordination and support in creating this opportunity.

-   **Dates:** January 28, February 4, 11, 25 and March 11, 2022
-   **Times:** 12:00-1:30pm PT
-   **Where:** remotely, via Zoom (from the browser)

**Plan.**

[Openscapes](https://openscapes.org/) is an approach for doing better science in less time. Through the Champions program we help research groups reimagine data-intensive science, develop modern skills that are of immediate value to them, and cultivate collaborative and inclusive research communities. The Champions Program is designed for you to all participate actively with your team and across teams in the cohort, so please come prepared to engage with your colleagues. Within your team and across teams we have a mix of backgrounds, technical/coding/data experience, responsibilities, and more -- this is intentional. You are all welcome here and provide value to our cohort; there are no technical prerequisites to participate.

You can learn more about past cohorts at [openscapes.org/blog](https://openscapes.org/blog) (including [NEFSC](https://www.openscapes.org/blog/2020/03/06/workshop-noaa-nefsc/), [NWFSC](https://www.openscapes.org/blog/2021/05/03/noaa-nwfsc-champions/), [NMFS](https://www.openscapes.org/blog/2021/11/12/noaa-nmfs-champions/), and [FDD](https://www.openscapes.org/blog/2021/11/12/fdd-champions/) cohorts), as well as [openscapes.org/media](https://openscapes.org/media).

**Preparing for our Cohort. This week, please**:

1.  **Check that you've received Google Calendar invites with Zoom links** **for our 5 Cohort Calls starting Jan 28**. You've also received invites for optional Coworking times in \~alternating weeks (described more below). If you have not received these invites, please let us know.

2.  **\[Book a 30-minute intro call on Jan 20 or 21\]** -- or suggest other times if that is not possible. These "1:1's" are a chance for your team to meet the Openscapes team, learn more about what to expect, start thinking about your goals, and ask any questions. Please discuss with your team and book a time (one time per team).

We'll email again following the intro calls with more information, and ask that you read [Lowndes et al 2017](https://www.nature.com/articles/s41559-017-0160): Our path to better science in less time using open data science tools before January 28.

**Additional Information.**

All Openscapes events abide by our [Code of Conduct](https://openscapes.org/code-of-conduct).

Will be recording all Cohort Calls. They will be available for you if you miss a meeting or to use as a reference, and to help us improve the program, but not shared publicly. If you have any concerns about being recorded, please let us know.

Schedule "Seaside Chats": In the alternating weeks when we do not meet as a cohort, your task will be to meet as a team to further discuss and apply what we learn to your work. We call these meetings "[Seaside Chats](https://github.com/Openscapes/seaside-chats)" and suggest you schedule them with your team now. People usually schedule these as 60-min meetings but you can make them whatever length you want. Megsie, Em, and Josh are able to join some of your Seaside Chats as well to help.

Optional "Coworking" sessions: times to implement what we've learned during Cohort Calls, where we work on our own projects at the same time together. Sometimes, this means quiet work with check-ins to break up, be accountable for, and get feedback on focused work, and sometimes this involves breakout rooms and screensharing to plan and problem solve.

Please let us know if you have any questions. Thank you for being a part of it; we have an exciting group assembled and we're looking forward to getting to know all of you and strengthening relationships within the Cohort.

Cheers,

Julie, Em, Josh, and Megsie
:::

### Week prior

\~1 week prior to the beginning of the Cohort, we email the full Cohort, welcoming everyone and sharing the plan and a few action items. This includes providing an email address that can access Google Drive and their GitHub username!

::: {.callout-tip collapse="true"}
## Example email to welcome (academic) cohort: week prior

**Welcome to Openscapes -- Fred Hutch Champions Cohort**

Hello All,

We are so excited to welcome you to the 2023 Fred Hutch Openscapes Champions Cohort! Our first Cohort Call is next week on August 29 and we wanted to share some information with you.

**Plan.**

[Openscapes](https://openscapes.org/) is an approach for better science for future us. Through the Champions Program we help researchers and those supporting research find each other and feel empowered to conduct collaborative data-intensive science. Openscapes Champions is not a typical workshop --- its cohort-based remote sessions for teams introduces concepts and workflows, facilitates teams to talk about problems, then go and solve them with accountability and support. It is a remote-by-design program, launched in 2019, and this is our 20th Cohort! Our Cohort is sponsored by [Fred Hutch Data Science Lab](https://hutchdatascience.org/), with Sean Kross and Monica Gerber supporting us and being a direct link between your needs and solutions at Fred Hutch.

**Before August 29, please**:

1.  **Check that you've received Google Calendar invites with Zoom links** for our 5 Cohort Calls starting August 29 as well as optional Coworking sessions in the weeks between Cohort Calls. If you have not received these invites, please let us know.

2.  **Complete your information in OpenscapesParticipants \[ 2023-fred-hutch \]** to make sure you can access the software we'll use (Google Drive and GitHub).

3.  **Read the [Openscapes Lesson Series](https://openscapes.github.io/series/) homepage** to learn more about what to expect (the purpose, outcomes, and process of our Cohort), and [**Lowndes et al 2017**](https://www.nature.com/articles/s41559-017-0160) "Our path to better science in less time using open data science tools" to see how a team transitioned shared workflows.

**Additional Information.**

All Openscapes events abide by our [Code of Conduct](https://openscapes.org/code-of-conduct).

Will be recording all Cohort Calls. They will be available for you if you miss a meeting or to use as a reference, and to help us improve the program, but not shared publicly. If you have any concerns about being recorded, please let us know.

Schedule "Seaside Chats": In the alternating weeks when we do not meet as a cohort, your task will be to meet as a team to further discuss and apply what we learn to your work. We call these meetings "[Seaside Chats](https://github.com/Openscapes/seaside-chats)" and suggest you schedule them with your team now (PIs do not need to attend).

The Champions Program is designed for you to all participate actively with your team and across teams in the cohort, so please come prepared to engage with your colleagues. Within your team and across teams we have a mix of backgrounds, technical/coding/data experience, responsibilities, and more -- this is intentional. You are all welcome here and provide value to our cohort; there are no technical prerequisites to participate.

**Meet the Openscapes team.**

We're the team you'll see most often on the calls, along with a few guest speakers:

-   [Julie Lowndes](http://jules32.github.cio/), Openscapes 

-   [Stefanie Butland](https://stefaniebutland.netlify.app/), Openscapes

-   [Sean Kross](https://seankross.com/), Fred Hutch Data Science Lab

-   [Monica Gerber](https://www.monicagerber.com/), Fred Hutch Data Science Lab

Please let us know if you have any questions. Thank you for being a part of it; we have an exciting group assembled and we're looking forward to getting to know all of you and strengthening relationships within the Cohort.

Cheers,

Julie, Stefanie, Sean, Monica
:::

### Day prior

::: {.callout-tip collapse="true"}
## Example email to welcome cohort: day prior

Hi All,

We're excited to meet you all with your teams as a full Cohort tomorrow at \[ Time \] Pacific Time!

You should have all received Google Calendar invites with the Zoom call-in information; call-in info is also pasted below. We've also just invited you to the \[ Openscapes_CohortCalls folder \] where all agendas and other documents will be organized throughout our Cohort.

Please also update your information in the \[\] OpenscapesParticipants spreadsheet \] and learn about the other participating teams at \[ https://openscapes.github.io/2021-sasi \].

Looking forward to it! Cheers, Julie, Erin, Lenny, and Emma

Zoom call-in information

\[ via web and phone \]
:::

## Guest teachers

We invite guest teachers to present topics during Cohort Calls, either from our existing slides or they can contribute their own on a similar topic. For example, Dr. Jessica Couture contributed a new slide deck on metadata and presented this during the [data strategies for future us](https://openscapes.github.io/series/data-strategies.html) lesson. Most of our guest teachers are Champions from previous cohorts (Jessica is a Champion from the 2019-inaugural cohort), and we are able to offer an honorarium for their time and expertise.

::: {.callout-tip collapse="true"}
## Example email to guest teacher

Subject: Invitation as guest teacher in Openscapes

Hi \[ potential guest teacher\],

How are you? I hope you've had a break this summer and are doing ok with everything going on.

Openscapes has a few Champions cohorts we're leading this fall, including one with researchers using fisheries dependent data in the US Northeast coordinated by Gavin Fay, Andy Jones, and Rachel Baum (here's the [cohort page](https://openscapes.github.io/2021-fdd/)).

We wanted to **invite you as a guest teacher** at one of these Cohort Calls for 20-25 minutes, presenting \~12 mins of slides and leading the following discussion (likely breakout groups and then group discussion). We're thinking of you joining the second call and presenting about [data strategies for future us](https://openscapes.github.io/series/data-strategies.html), or the third and presenting about [coding strategies for future us](https://openscapes.github.io/series/coding-strategies.html). You could either present from our existing slide decks, or present something on-theme from your work, and we can help you with the format and timing. Cohort Calls 2 & 3 are on October 1 & 15 from 12-1:30pm ET (exact time TBD but you're welcome to just attend for your part). We are able to offer an honorarium as well.

We're excited to hear your ideas, and if this isn't the right thing now to think about if there's another way we can involve you in the future if you'd like. We'd love to chat with you about it in any case, would you be able to suggest a few times for a 30-minute call?

Cheers,

Julie and Erin
:::

And some follow up advice to help strategize preparing:

::: {.callout-tip collapse="true"}
## Example email advice to guest teacher

I'm following up on our conversation about your Data Strategies lesson for the CA Water Boards Openscapes Cohort. Here's my advice brain-dump ;-) 

The most important point is that you don't need to make up new material or create an activity. We teach these lessons from [our existing slide deck](https://docs.google.com/presentation/d/1WJzVMg1Ps2cHG0G6D5kpnL-OCJ-wVBILMqtmzDQxEgU/). Julie taught from this deck to the previous Water Boards Cohort and I did the same for another cohort. The speaker notes have some guiding language. We try to basically say what's on the slides and we pepper them (within the time limit) with personal examples or anecdotes. 

The[Data Strategies page](https://openscapes.github.io/series/core-lessons/data-strategies.html) in our Openscapes Champions Lesson Series, has a narrative that essentially follows the slides. Near the top of that page is a link to a recording of Ileana Fenwick teaching from the same slide deck. The first time I prepared to give that lesson (the only time so far), I started by watching Ileana's recording and reading the couple of papers/ blog posts in the slides. Tip: when a slide has a list of 10 tips, you don't need to say them all. You might say "this paper gives 10 tips for ... . I want to highlight 3". Then I said the tip and gave an example of how I've used it in my work. That's the way you get to make the same slide deck be relatable and allow you to share your own knowledge and experiences.

The Water Boards sessions are in Microsoft Teams. There are \~ 20 folks. When teaching, you don't share your screen - people follow along by clicking through the slide deck themselves - that means it's easier to use speaker notes if you like to do that. Anna Holder, the lead, is such a warm facilitator with a great sense of humour that shows through. She makes for a really positive teaching experience. 

Looking forward to seeing you soon,

Stef
:::

Followup email the week before:

::: {.callout-tip collapse="true"}
## Example email to guest teacher: week prior

Hi Emily and Chanté,

We're excited about your guest teaching and wanted to check in about it. We've had a good first week and two GitHub Clinics and people are excited to learn from how you both work!

I've just shared our \[draft Agenda\] for this second Cohort Call on October 1, with Emily planned for 11:45-12:20. Would you be able to share your plan by Sept 30 and we can iterate? We can work with you and iterate the discussion prompts following your slides if you'd like, and whether it would make most sense to have more of a group discussion rather than breakouts.

How does all this sound? Happy to meet to chat about it/review together if you have questions, or continue discussions by email.

Thank you!

Cheers,

Julie
:::
