---
title: Openscapes resources
---

Our main Openscapes website [**Resources**](https://www.openscapes.org/resources) page has some resources meant to welcome environmental scientists who are newly onboarding to open data science.

We encourage people to reuse and remix our approach. To help, we have created template Google docs for our [**Openscapes Champions Lesson Series**](https://openscapes.github.io/series/) agendas, debriefs, and group coworking sessions ([Google drive folder](https://drive.google.com/drive/u/1/folders/1Iq8tj81TSfr-RstphVTZWoz783xpJMOb)).

Our [Openscapes GitHub Organization](https://github.com/openscapes) has pinned repositories of interest, including the [teaching-learning-resources](https://github.com/openscapes/teaching-learning-resources) repo where we use [Issues](https://github.com/openscapes/teaching-learning-resources/issues) to jot down specific tools or learning resources for open, reproducible, inclusive science.

We also have a public [Openscapes Zotero library](https://www.zotero.org/groups/4118402/openscapes/library) linking publications, talks, and curricula. And, a public [Openscapes Spotify Playlist](https://open.spotify.com/playlist/7rAl8ORlMJbqa9IylFhSwd?si=5042f14a9b8c4dcc&nd=1) of favorite pump-up songs from our cohorts.
