---
title: Mentors Skills
---

## Winter 2025 NOAA Fisheries Mentors Skills and Practices

### Call 1 

Reconnecting together, welcoming new Mentors, and focusing on building our community and goals for the next year.

-   **Getting into a mindset for the call** - use a framework for silent reflection at top of call.

-   **Speaking up/sharing about yourself for 3 minutes** - a challenge for some to take up that space, a challenge for others to limit to that space.

-   **Practicing asking questions** -“could you share background on this?”

-   **Being a learner and leader at the same time** - using this group to help reduce feelings of overwhelm. Learn something then turn around and teach someone else.

-   **Learning from other organizations experiences** - seeing what is possible (for example, from NASA) and from where NOAA leads

-   **Live contributing to group visioning in 3 phases** - using a new tool to brainstorm all ideas; pause and read; move ideas into common themes

-   **Adjusting time on the fly in the shared agenda and verbally** - open facilitation

### Call 2

Continue strategic thinking and goal-setting and discuss software peer review.

-   **Getting into a mindset for the call** - use the “mind dump” for silent reflection and harnessing our focus at top of call

-   **Define specific and ‘small-enough’ goals to make progress on larger objectives -** loosely using the SMART framework

-   **Moving quickly into breakouts when time is limited** - make the most of time to work together

-   **Making ideas, goals, and resources more visible so others can contribute** - use GitHub Project board and Issues 

-   **Learning about software peer review from rOpenSci** - the value of borrowing and adapting standards

-   **Supporting each other on the fly verbally as we updated the agenda to accommodate a concurrent NWFSC all-hands meeting** - open facilitation

## Fall 2023 NOAA Fisheries Mentors Skills and Practices

In fall 2023, we had five Mentor Calls as a full community. We detail the **skills and practices** Mentors experienced and experimented with in each Call, in the [NMFS Openscapes website](https://nmfs-openscapes.github.io/mentors/mentor-calls.html).

### Agendas

[Public copy of Agendas](https://docs.google.com/document/d/16F5nt0TNfU66OakTBmuyrZkASv9vKDMGkXjb_eJY_78/edit?tab=t.0) for NMFS Openscapes Mentor Calls and Themed Seaside Chats.

### Slides

1.  [Openscapes Mindset for Mentors](https://docs.google.com/presentation/d/1EGXrIRzTptY3gcTlG20I7oW5oCzdIS9DB255AHjJ77U/edit#slide=id.p)
2.  [Open and Collaborative Communities for Mentors](https://docs.google.com/presentation/d/1rQ7N51AQl-A73SZnvRuPv2QJobIinvksKjIriQn0YNM/edit#slide=id.p)

## Engaging supervisors

-   Include a deadline
-   Say please forward to all supervisors

## Listening

Credit to [Tara Robertson](https://tararobertson.ca/) for leading some Openscapes Mentors in “Mentoring with a Coach Approach” Series. Blog post: [How coaching skills have made us better open data science mentors](https://openscapes.org/blog/2023-05-17-mentor-coach/)

**Listening**

How we listen differs whether we are in mentor-mode or coach-mode:

-   When we listen as mentors, we’re trying to understand where our expertise can help someone solve a problem.

-   When we’re listening as coaches, we’re trying to help the other person define their problem, and tap into their own wisdom to find their solution, likely outside of our domain expertise.
