---
title: "Onboarding Mentors"
---

## 

TODO: Maybe add: https://github.com/NASA-Openscapes/NASA-Openscapes.github.io/blob/main/mentors.qmd#L90

## Create a Participants List Spreadsheet

We create a spreadsheet called `OpenscapesParticipantsList [ nasa-mentors ]`

Headers: cohort first last email email-2 institution GitHub - green means added to GitHub nasa-openscapes Org and 2i2c Twitter

## Create a Google Group with Mentors

For NASA, we created a Google Group so we could easily add mentors to Google Folders and Calendars. 

This hasn't worked perfectly because not everyone can use their work address to access Google things. We collect a second email address in the ParticipantsList spreadsheet, but if we use Google Groups we need to make sure that everyone's Google-access emails are included in the Google Group.

## 1:1 calls

Example doc

::: {.callout-note collapse="true" icon="false"}
## 1:1 agenda example

**SEDAC -- Openscapes 1:1 meetings**

Zoom:

\

**Aug 24, 2023**

Name, Julie Lowndes

30 minutes

**Purpose:** Openscapes overview and getting to know each other

\
**Agenda**

**Introductions - what brings you to NASA Openscapes?**

-   

-   Julie marine ecologist turned open science person, NASA Openscapes with Erin Robinson

**NASA-Openscapes Overview**

-   <https://nasa-openscapes.github.io> **(**[recent presentations](https://nasa-openscapes.github.io/about.html)) 

-   [ESIP Session at Winter 2023](https://2023januaryesipmeeting.sched.com/event/1EwXx) - 3 Approaches for the Year of Open Science

-   [NASA OSS Working Group Talk](https://docs.google.com/presentation/d/1BK678MADRg6QkejRQI_5KREGn6DzzQqAS4StsjXmi-k/edit#slide=id.g1b5922f14f8_0_83) 

-   Our goal: to support the work you are already doing. Using Openscapes model, iterating and growing and evolving with Mentors

-   "Not in addition to our jobs" - and connects to other DAACs

-   Professional dev, relationships with other DAAC mentors, and ability to work with "early adopter" scientists

Broader background about Openscapes: <https://openscapes.org> 

**DAAC activities, skills & software** (help us plan clinics/co-working/what do you all collectively want to do?)

-   GitHub Usernames:

-   

-    

**NASA activities**

-   Are you working with ARSET, DEVELOP, TOPS, SERVIR?

    -   

-   Are you doing anything cross-DAAC?

    -   

Are there hurdles that we should be aware of?

-   

-   

**Next steps**

-    

-    

**Draft Calendar (in progress)**

-   New mentors onboarded in late Summer 2023 

-   

**Discussion / Questions**

-    

-    

-   
:::

## Post 1:1 Followup Checklist

-   Send Welcome email (examples below)

    -   Ask for: GitHub Username, email-2

<!-- -->

-   Add to calendar invites
-   Add to google group
-   Add to Slack
-   Invite to Carpentries Instructor Training
-   Add to 2i2c as an administrator <https://openscapes.2i2c.cloud/admin>
-   Add to GitHub Org

::: {.callout-note collapse="true" icon="false"}
## Intro email example

Hi V,

It was great to meet you; your colleagues said you're able to join the NASA Openscapes Mentors from PO.DAAC -- we're super excited, welcome! We're preparing for a Sept 20 kickoff to onboard new mentors, and have a light outline of plans here: https://nasa-openscapes.github.io/mentors.html#current-activities.

This cross-DAAC mentor community is creating & teaching resources to help researchers migrate workflows to the cloud. The expected time commitment is 3 days/month per year (and this ebbs and flows with your deadlines). This accounts for \~6 hours/month of synchronous calls with the rest of the time being self-directed towards improving support approaches for specific DAACs. You'll be collaborating with others at your DAAC as well as across DAACs and the broader open science community. Please talk with your supervisor to make sure you are supported in alignment with your job; we will share with EOSDIS and HQ as well.

We'll soon add you to calendar invites. If you'd have time for a 1:1 intro in the next few weeks, that would be super -- we can share more and answer any questions you have ahead of our Sept 20 kickoff. The week of Sept 5 I'm available most days between 11-2pm PT if you'd have 30 minutes to chat.

Cheers, Julie
:::

::: {.callout-note icon="false"}
## Followup email example

Subject: Welcome to the NASA Openscapes Mentor Community!

Hi Sean, Alicia, Guoqing,

It was great to meet you and we're really excited Guoqing will be joining the NASA Openscapes Mentor community from OBDAAC! I've cc'd co-lead Erin Robinson and our colleague Stefanie Butland here as well.

**Please look out for invitations to our Calendar and Slack**. Guoqing, could you please share your GitHub username and an email address for Google Drive (if not this one)?. We'll then give you access to our 2i2c JupyterHub and other things listed in our [how we onboard](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/onboarding.html) documentation – this is part of the Earthdata Cloud Cookbook that is the main place for all cloud resources the Mentors are developing. As one professional development opportunity, we partner with The Carpentries, a nonprofit that teaches introductory coding skills around the world. They will announce new dates for Instructor Training next month and we will share information for how to sign up.

**We'll have our first Fall kickoff meeting September 20**, but you're welcome to join sessions anytime before then. Please also let us know if there are additional colleagues who are able to join.

We're really looking forward to working with you! 

Cheers, 

Julie
:::

::: {.callout-note collapse="true" icon="false"}
## Followup email example with Carpentries

Subject: Welcome to the NASA Openscapes Mentor Community!

Hi Kytt and Juan,

It was great to meet you and we're really excited you'll be joining the [NASA Openscapes](https://nasa-openscapes.github.io/) Mentor community from SEDAC!

**Please look out for invitations** to our Calendar and Slack. Could you please share your GitHub username and an email address for Google Drive (if not this one)?. We'll have our first Fall kickoff meeting September 20, but you're welcome to join sessions anytime before then. You can also familiarize yourself with [how we onboard](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/onboarding.html) --- this is part of the Mentors' Earthdata Cloud Cookbook.

**Carpentries Instructor Training** - As part of our NASA grant, we partner with [The Carpentries](https://carpentries.org/), a nonprofit that teaches introductory coding skills around the world. This remote training is not coding-specific, but it is a pedagogical approach to teaching technical topics. If you would like to sign up, please follow the 2-step process below. Our membership renews Sept 14; if you have trouble signing up using our code please let me know and I can help get it sorted.

1)  Register for the event of your choice on our [Instructor Training event calendar](https://carpentries.github.io/instructor-training/training_calendar#upcoming-instructor-training) with the code: **OUR-CODE-HERE**. New events are added to this calendar in December, March, June, and September.

2)  Complete Carpentries [profile-creation form](https://amy.carpentries.org/forms/request_training/) using the same code. **Please note**: Registration secures their seat; profile creation enables us to record their attendance and track their progress toward certification.

We're really looking forward to working with you! Cheers, Julie
:::

Update https://nasa-openscapes.github.io/mentors.html#mentor-cohort
