---
title: "Engagement"
format: html
---

When we are engaging with a new community, these are the things that we share in our first planning meetings. Our goals are to introduce our process, discuss with partners, and get feedback on our engagement strategy. If we are planning a Champions Cohort, we also share proposed date-times.

We’re getting to know new people. And they’re getting to know us. We bring our warmth and competence to these meetings with the goal of building mutual understanding, care, and trust.

## Example Kickoff Meeting Agenda

Goal: Introduce our Openscapes process, discuss with you, and get feedback from you on our proposed dates and engagement strategy for the Cohort.\

-   Quick intros - welcome Stef (5 min)

-   Openscapes Champions process - focus on participants (5 min)

    -   We have a process we’ve used with 29 Cohorts with \~10 different science groups with different research domains. Our process is all open and accessible to you — and we are intentional not to overload. We will onboard you as we go, sequencing what we are focused on.

    -   We know to be successful we need to gain a depth of understanding of who you imagine being the participants in this Champions Cohort. 

    -   Right now, we need to focus on audience. Not for lesson design, but for our participant engagement strategy. We approach engagement from a mindset that participants want to learn, don’t fear change, but are very limited on time. The antidote to this challenge is trust.

        -   We need people to trust us with their time. We can start focusing on "transitive trust" - building real relationships that are nurtured from existing communities and collaborations.

-   **1) Reviewing audience and approach** (screenshare spreadsheet \[ dev below and link\])

    -   What makes these people a group? What binds them together? 

    -   Do Science Hub researchers meet periodically/regularly? 

    -   What are some collaborations within the group that already exist?

    -   What else would we need to know before we emailed these participants? 

    -   Do you have a sense of what tools and approaches and processes they say they need? 

-   **2) Setting Champions Cohort date-times**

-   We've found it's best to engage with folks when there are dates they can commit "yes" to, and they can share.

    -   We propose ESA EarthCODE Openscapes Champions Cohort will run from **April - June 2026**. We will meet as a Cohort via Zoom five times over two months for 1.5 hours, on alternating Wednesdays or Thursdays. Would these times work for all of us: 

    -   **Option 1) Wednesdays at 14-15:30 GMT**

    -   Dates: April 15, 29, May 13, 27, June 10

    -   **Option 2) Thursdays at 12-13:30 GMT**

    -   Dates: April 16, 30, May 14, 28, June 11

    -   **Option 3) Thursdays at 14-15:30 GMT**

    -   Dates: April 16, 30, May 14, 28, June 11

-   **3) Setting info session webinar - give a presentation to the Science Hub researchers.**

-   Join an existing session? Who organizes it? What do they need from us (bio, abstract)?

::: {.callout-tip collapse="true"}
## Email sent to partners to schedule kickoff meeting

Subject: Openscapes Champions Planning

Hi All,

I hope you’re having a good week. Our Openscapes team has started our planning process for the Champions Cohort and are excited!

We’d like to share about this in our next meeting. Our goals are to introduce our process, discuss with you, and get feedback from you on our proposed dates and engagement strategy for the Cohort. Another goal is to introduce you to my colleague Stefanie who leads the infrastructure setup for the Cohort.

Cheers, Julie
:::

## Engagement Spreadsheet

*TODO: maybe a more distinguishable name à la "Cohort Calendaring"*

TODO: dev more

Tabs:

-   stakeholder groups

-   participants - starting from highest priority group. Can use ORCID website to quickly review their fields

-   checklist
